#!/usr/bin/env bash
# shellcheck disable=SC2086
set -e

## Description: Initialize TYPO3 installation
## Usage: init-typo3
## Example: ddev init-typo3

readonly dbHost="db"
readonly dbUser="db"
readonly dbPassword="db"
readonly dbName="db"
readonly dbCredentials="-h${dbHost} -u${dbUser} -p${dbPassword}"
readonly typo3Binary="/var/www/html/vendor/bin/typo3"

function _progress() {
    printf "%s... " "$1"
}

function _done() {
    printf "\e[32mDone\e[39m\n"
}

_progress "Creating empty database"
mysql -Nse "SHOW TABLES" $dbCredentials "$dbName" | while read -r table; do
    mysql -e "DROP TABLE ${table}" $dbCredentials "$dbName"
done
_done

export TYPO3_DB_DRIVER=mysqli
export TYPO3_DB_USERNAME="$dbUser"
export TYPO3_DB_PASSWORD="$dbPassword"
export TYPO3_DB_PORT=3306
export TYPO3_DB_HOST="$dbHost"
export TYPO3_DB_DBNAME="$dbName"
export TYPO3_SERVER_TYPE=apache
export TYPO3_PROJECT_NAME="EXT:scheduler_as_code"
export TYPO3_SETUP_ADMIN_USERNAME="${TYPO3_SETUP_ADMIN_USERNAME:-admin}"
export TYPO3_SETUP_ADMIN_PASSWORD="${TYPO3_SETUP_ADMIN_PASSWORD:-Passw0rd!}"
export TYPO3_SETUP_ADMIN_EMAIL="${TYPO3_SETUP_ADMIN_EMAIL:-admin@example.com}"

_progress "Setting up TYPO3 installation"
    "$typo3Binary" setup --no-interaction --force --quiet --create-site="https://${DDEV_HOSTNAME}/"
_done

_progress "Flushing caches"
    "$typo3Binary" cache:flush --quiet
_done

printf "\nBackend: \e[36mhttps://%s/typo3/\e[39m (%s)\n" "$DDEV_HOSTNAME" "$TYPO3_SETUP_ADMIN_USERNAME"
